version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile_django
    depends_on:
      - postgres
    command: >
     bash -c "/bin/bash"
    tty: true
    stdin_open: true
    volumes:
      - "./travel/test-reports:/opt/apps/travel/test-reports"
    ports:
      - "80:80"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes:
      - ./pg_scripts/install_ci.sql:/docker-entrypoint-initdb.d/install.sql
    # ポートは確認用なので開けなくも良い
    ports:
      - "5432:5432"
