version: '3'

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_django
    expose:
      - "3031"
    command: bash -c "
      cd travel
      && python manage.py collectstatic --noinput --settings=setting.settings_stg
      && python manage.py migrate --settings=setting.settings_stg
      && gunicorn setting.wsgi_stg -b 0.0.0.0:3031
      "
    volumes:
      - "staticdata:/opt/static/"
    depends_on:
      - postgres
      - redis
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "443:443"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "staticdata:/opt/apps/static/"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes:
      - ./pg_scripts/install_stg.sql:/docker-entrypoint-initdb.d/install.sql
    env_file: ./travel/.env.postgres
    ports:
      - "5432:5432"
  redis:
    build:
      context: .
      dockerfile: Dockerfile_redis
    env_file: ./travel/.env.redis
    command: >
      bash -c "
      redis-server --requirepass $${REDIS_PASSWORD}
      && /bin/bash"
    tty: true
    stdin_open: true
    ports:
      - "6379:6379"

volumes:
  # postgres_data:
  staticdata:
