version: '3'

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_django
    expose:
      - "3031"
    command: sh -c "
      cd travel
      && python manage.py collectstatic --noinput
      && python manage.py migrate
      && gunicorn setting.wsgi -b 0.0.0.0:3031
      "
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
