FROM python:3.6-alpine

ENV APP_PATH /opt/apps
COPY . $APP_PATH/
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev \
    && pip install --no-cache-dir -r $APP_PATH/requirements.txt

WORKDIR $APP_PATH
