version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile_django
    command: >
      sh -c "
      apk update
      && apk add chromium chromium-chromedriver
      && pip install --no-cache-dir -r requirements_dev.txt
      && cd travel && python manage.py migrate
      --settings=setting.settings_dev
      && sh"
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis
    volumes:
      - ".:/opt/apps/"
    ports:
      - "80:80"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes:
      - ./pg_scripts/install_dev.sql:/docker-entrypoint-initdb.d/install.sql
      - "/tmp/postgres-data:/var/lib/postgresql/data"
    env_file: ./travel/.env.postgres
    ports:
      - "5432:5432"
  redis:
    build:
      context: .
      dockerfile: Dockerfile_redis
    env_file: ./travel/.env.redis
    command: >
      bash -c "
      redis-server --requirepass $${REDIS_PASSWORD}
      && /bin/bash"
    tty: true
    stdin_open: true
    ports:
      - "6379:6379"
