version: '3'

services:
  django:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_RESOURCE_NAME_PREFIX_DJANGO:$CIRCLE_SHA1
    ports:
      - "3031:3031"
    command: sh -c "
      cd travel
      && python manage.py collectstatic --noinput
      && python manage.py migrate
      && gunicorn setting.wsgi -b 0.0.0.0:3031
      "
  nginx:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_RESOURCE_NAME_PREFIX_NGINX:$CIRCLE_SHA1
    ports:
      - "80:80"
    command: sh -c "
      nginx -g 'daemon off;'"
