version: '3'

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_django
    expose:
      - "3031"
    command: bash -c "
      cd travel
      && python manage.py collectstatic --noinput
      && python manage.py migrate
      && gunicorn setting.wsgi -b 0.0.0.0:3031
      "
    volumes:
      - "staticdata:/opt/static/"
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./nginx_setting/product/nginx/:/etc/nginx/"
      - "staticdata:/opt/apps/static/"

volumes:
  staticdata:
