version: '3'

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_django
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes:
      - ./pg_scripts/install_ci.sql:/docker-entrypoint-initdb.d/install.sql
    environment:
      - POSTGRES_USER=travel_ci
      - POSTGRES_PASSWORD=travel_ci
      - POSTGRES_DB=djangodb_ci
    # ポートは確認用なので開けなくも良い
    ports:
      - "5432:5432"
