version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile_django
    depends_on:
      - postgres
      - redis
    command: >
     bash -c "/bin/bash"
    tty: true
    stdin_open: true
    volumes:
      - "./travel/test-reports:/opt/apps/travel/test-reports"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    volumes:
      - ./pg_scripts/install_ci.sql:/docker-entrypoint-initdb.d/install.sql
    ports:
      - "5432:5432"
  redis:
    build:
      context: .
      dockerfile: Dockerfile_redis
    command: >
      bash -c "
      redis-server --requirepass password
      && /bin/bash"
    tty: true
    stdin_open: true
    ports:
      - "6379:6379"
