# Generated by Django 2.2.4 on 2019-10-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(help_text='8~15文字の間', max_length=255, verbose_name='パスワード'),
        ),
    ]
