# circleCIのバージョン指定
version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
# Djangoのテストを実行
      - checkout
      - run:
          name: docker-compose up
          command: |
            docker-compose -f docker-compose_ci.yml up -d
      - run:
          name: docker-compose generate secret key
          command: |
            docker-compose -f docker-compose_ci.yml run --rm django sh -c "cd travel/setting && python generate_secretkey_setting.py > settings_ci.py"
      - run:
          name: docker-compose run migrate
          command: |
            docker-compose -f docker-compose_ci.yml run --rm django sh -c "cd travel && python manage.py migrate --settings=setting.settings_ci"
      - run:
          name: docker-compose run test
          command: |
            docker-compose -f docker-compose_ci.yml run --rm django sh -c "cd travel && python manage.py test --settings=setting.settings_ci"
      - run:
          name: docker-compose down
          command: docker-compose -f docker-compose_ci.yml down
# EC2にSSH接続し、デプロイを実行
  # deploy:
  #   machine:
  #     image: circleci/classic:edge
  #   steps:
  #     - checkout
  #     # CircleCIに登録した秘密鍵を呼び出す
  #     - add_ssh_keys:
  #     - run: ssh ${USER_NAME}@${HOST_NAME} 'cd todoList && git pull && docker-compose run python ./manage.py migrate'

# テストが成功した場合のみ、deployを実行するようにする
# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           # masterブランチがpushされた場合のみdeployするようにする
#           filters:
#             branches:
#               only: master
