version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    environment:
      DOCKER_COMPOSE: docker-compose -f docker-compose_ci.yml
      SETTINGS_CI: --settings=setting.settings_ci
      REPORTS_DIR: test-reports
      TEST_XML: test-reports/test.xml
      REPORTS_INTEG_DIR: test-reports/integtest
      REPORTS_UNIT_DIR: test-reports/unittest
      MNG_PY: python manage.py
# アプリのビルド、テスト実行
    steps:
      - checkout
      - run:
          name: docker-compose up
          command: |
            $DOCKER_COMPOSE up -d
      - run:
          name: docker-compose install chromium and driver
          command: >
            $DOCKER_COMPOSE exec django sh -c
            "apt-get -y update
            && apt-get install -y chromium chromium-driver"
      - run:
          name: docker-compose install requirements
          command: >
            $DOCKER_COMPOSE exec django sh -c
            "pip install --no-cache-dir -r requirements_dev.txt"
      - run:
          name: docker-compose exec migrate
          command: >
            $DOCKER_COMPOSE exec django sh -c
            "cd travel && $MNG_PY migrate $SETTINGS_CI"
      - run:
          name: docker-compose exec unittest
          command: >
            $DOCKER_COMPOSE exec django sh -c
            "cd travel
            && coverage run --source='.'
            --rcfile='test/setting/.coveragerc'
            manage.py test test.unittest $SETTINGS_CI --keepdb
            && mv $TEST_XML $REPORTS_UNIT_DIR/unittest.xml"
      - run:
          name: docker-compose exec integration test
          command: >
            $DOCKER_COMPOSE exec django sh -c
            "cd travel
            && $MNG_PY test test.integtest.accounts
            $SETTINGS_CI --keepdb
            && mv $TEST_XML $REPORTS_INTEG_DIR/accounts.xml
            && $MNG_PY test test.integtest.travel.test_place_list
            $SETTINGS_CI --keepdb
            && mv $TEST_XML $REPORTS_INTEG_DIR/travel_place_list.xml
            && $MNG_PY test test.integtest.travel.test_saved_place_list
            $SETTINGS_CI --keepdb
            && mv $TEST_XML $REPORTS_INTEG_DIR/travel_saved_place_list.xml
            && $MNG_PY test test.integtest.travel.test_setting
            $SETTINGS_CI --keepdb
            && mv $TEST_XML $REPORTS_INTEG_DIR/travel_setting.xml"
      - run:
          name: docker-compose generate test-html-report
          command: >
            $DOCKER_COMPOSE exec django sh -c
            "cd travel
            && junit2html $REPORTS_UNIT_DIR/unittest.xml
            $REPORTS_UNIT_DIR/html/unittest.html
            && junit2html $REPORTS_INTEG_DIR/accounts.xml
            $REPORTS_INTEG_DIR/html/accounts.html
            && junit2html $REPORTS_INTEG_DIR/travel_place_list.xml
            $REPORTS_INTEG_DIR/html/travel_place_list.html
            && junit2html $REPORTS_INTEG_DIR/travel_saved_place_list.xml
            $REPORTS_INTEG_DIR/html/travel_saved_place_list.html
            && junit2html $REPORTS_INTEG_DIR/travel_setting.xml
            $REPORTS_INTEG_DIR/html/travel_setting.html"
      - run:
          name: docker-compose generate coverage-html-report
          command: >
            $DOCKER_COMPOSE exec django sh -c
            "cd travel && coverage html -d $REPORTS_DIR/coverage/"
      - run:
          name: docker-compose down
          command: $DOCKER_COMPOSE down

      - store_test_results:
          path: ./travel/test-reports

      - store_artifacts:
          path: ./travel/test-reports
# EC2にSSH接続し、デプロイを実行
  # deploy:
  #   machine:
  #     image: circleci/classic:edge
  #   steps:
  #     - checkout
  #     # CircleCIに登録した秘密鍵を呼び出す
  #     - add_ssh_keys:
  #     - run: ssh ${USER_NAME}@${HOST_NAME} 'cd todoList && git pull && docker-compose run python ./manage.py migrate'

# テストが成功した場合のみ、deployを実行するようにする
# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           # masterブランチがpushされた場合のみdeployするようにする
#           filters:
#             branches:
#               only: master
