# Generated by Django 2.2.4 on 2019-10-11 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='設定の名称', max_length=20, verbose_name='設定名')),
                ('radius', models.IntegerField(default=500, help_text='現在地からの半径をm単位で指定する。10~10000の間で指定。', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)], verbose_name='半径')),
                ('max_show_num', models.IntegerField(default=5, help_text='最大で表示する件数。最大値は500。', validators=[django.core.validators.MaxValueValidator(500)], verbose_name='最大表示件数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AppUser')),
            ],
            options={
                'verbose_name': '設定',
                'verbose_name_plural': '設定',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='場所の名称', max_length=255, verbose_name='場所名')),
                ('saved_time', models.DateTimeField(default=django.utils.timezone.now, help_text='保存された時刻', verbose_name='保存日時')),
                ('linkUrl', models.URLField(blank=True, help_text='リンク先のURL', null=True, verbose_name='記事URL')),
                ('imageUrl', models.URLField(blank=True, help_text='サムネイル画像のURL', null=True, verbose_name='画像URL')),
                ('extract', models.CharField(blank=True, help_text='場所の簡単な説明', max_length=128, null=True, verbose_name='説明')),
                ('latitude', models.FloatField(blank=True, default=0, help_text='10進数表記', null=True, verbose_name='緯度')),
                ('longtitude', models.FloatField(blank=True, default=0, help_text='10進数表記', null=True, verbose_name='経度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AppUser')),
            ],
            options={
                'verbose_name': '気になる場所リスト',
                'verbose_name_plural': '気になる場所リスト',
            },
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='name_must_be_unique'),
        ),
    ]
