# Generated by Django 2.2.4 on 2019-10-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='extract',
            field=models.CharField(blank=True, help_text='場所の簡単な説明', max_length=256, null=True, verbose_name='説明'),
        ),
    ]
