# Generated by Django 2.2.8 on 2020-01-12 05:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191020_1811'),
        ('travel', '0002_auto_20191012_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(help_text='コメント', max_length=512, validators=[django.core.validators.MaxLengthValidator(512)], verbose_name='コメント')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, help_text='コメントされた時刻', verbose_name='コメント日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AppUser')),
            ],
            options={
                'verbose_name': 'コメント',
                'verbose_name_plural': 'コメント',
            },
        ),
        migrations.CreateModel(
            name='SharedPlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='場所の名称', max_length=255, verbose_name='場所名')),
                ('linkUrl', models.URLField(blank=True, help_text='リンク先のURL', null=True, verbose_name='記事URL')),
                ('imageUrl', models.URLField(blank=True, help_text='サムネイル画像のURL', null=True, verbose_name='画像URL')),
                ('extract', models.CharField(blank=True, help_text='場所の簡単な説明', max_length=256, null=True, verbose_name='説明')),
                ('latitude', models.FloatField(blank=True, default=0, help_text='10進数表記', null=True, verbose_name='緯度')),
                ('longtitude', models.FloatField(blank=True, default=0, help_text='10進数表記', null=True, verbose_name='経度')),
                ('prefecture', models.CharField(max_length=4, null=True, verbose_name='都道府県')),
                ('city', models.CharField(max_length=10, null=True, verbose_name='市区町村')),
            ],
            options={
                'verbose_name': 'シェアされた場所',
                'verbose_name_plural': 'シェアされた場所',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(help_text='市区町村の名称', max_length=10, null=True, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='place',
            name='prefecture',
            field=models.CharField(help_text='都道府県の名称', max_length=4, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='max_show_num',
            field=models.IntegerField(default=5, help_text='最大で表示できる件数です。最大値は500です。', validators=[django.core.validators.MaxValueValidator(500)], verbose_name='最大表示件数'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='radius',
            field=models.IntegerField(default=500, help_text='現在地からの半径をm単位で指定します。10~10000の間が設定できます。', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)], verbose_name='半径 (m)'),
        ),
        migrations.CreateModel(
            name='PlaceComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_place', models.CharField(help_text='場所の名称', max_length=255, verbose_name='場所名')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Comment')),
            ],
            options={
                'verbose_name': 'シェアされた場所とコメントの紐づけ',
                'verbose_name_plural': 'シェアされた場所とコメントの紐づけ',
            },
        ),
    ]
